os: linux
arch: amd64
dist: xenial
language: android
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
- sudo apt update
- sudo apt install -y software-properties-common
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt update
- sudo apt install -y python3.9
- sudo apt install -y python3-pip
- nvm install node
- node --version
- pip3 install --user awscli
script:
  - echo Hello